### PR TITLE
Update to custom-functions-metadata 0.5.1

### PR DESCRIPTION
**Pull request by akrantz**

### CODE REVIEW

**Comment by Zlatkovsky** [comment]
@akrantz , do you also need to update the place where you call the `parseTree` function or whatever?

**Comment by Zlatkovsky** [comment]
If you do that, then I can take over your branch/PR and add the setting UI on top of that very easily.

**Comment by akrantz** [comment]
@Zlatkovsky Updated.

**Comment by Zlatkovsky** [comment]
Closing this PR in favor of #739 (which contains all of the same changes + my tweak on top of it)

**Pull request closed without merging**
