### PR TITLE
Translation to German for the meta data for the store

### PR DESCRIPTION
**Pull request by maninweb**
## Description
Translation to German for the meta data for the store.

## Related Issue
N/A

## Motivation and Context
So that it appears on the German version of the store.

## How Has This Been Tested?
N/A

## Screenshots (if appropriate):
3 screenshots in German for use in the store.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Translation
## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Notes
The files include the version for `de-de` (Germany). I've seen that the store is also available for `de-at` (Austria) and `de-ch` (Switzerland). In case a version for Austria and Switzerland would have to be addressed by their own in the store, the files for Germany can also be used, as the translation is the same for those countries.

### CODE REVIEW

**Comment by Zlatkovsky** [comment]
@saunders77 , FYI that Mourad has made the changes.  Merging now.  Btw, did you add to the translation doc the part about needing the description and images?

**Comment by Zlatkovsky** [comment]
Also @saunders77 , once I merge this in, do you want to rename the folder (and your en-us one) to just "en" and "de", to correspond with the store language entries?  If we do start specializing the locales, we can then rename just the specialized ones (e.g., "en-gb")

While you're renaming folders, I would also use a hyphen in "store-metadata" instead of an underscore.  That is the way of the web...

**Comment by saunders77** [comment]
@Zlatkovsky :

Yes, I added the instructions to the translation doc.

@locale-specific paths: that's the standard way Office works and it's the standard way the internet works: languages are locale-specific.

@store-metadata: what about our top-level node_modules folder? It would look weird to have:
`/store-metadata/`
`/node_modules/`

**Comment by Zlatkovsky** [comment]
@saunders77 , for locale-specific paths:  yes, you can use locale in addition to language, but it's also ok to have just language (which essentially is the logical equivalent of "en-*").  Per the StackOverflow thread (https://stackoverflow.com/questions/44964786/localizing-manifest-files-for-an-office-js-add-in), the manifest can also do just the language, not locale.  Though perhaps, if that answer is incorrect, that explains the issue https://github.com/OfficeDev/script-lab/issues/500.  I wonder if it would work if it _was_ labeled as "de-de", for example.  Could you look into that issue?

For the folder name.  OK, fair enough.  I will admit that I always found "node_modules" naming awkward, but it's true that it is there.  Fine, we can keep it.

**Pull request merged**
