### PR TITLE
Update to custom-functions-metadata@0.0.16

### PR DESCRIPTION
**Pull request by akrantz**

### CODE REVIEW

**Comment by akrantz** [comment]
@Zlatkovsky I saw today in another repo that you can add a .github/CODEOWNERS file and it will add the code owners as reviews on pull requests.

**Comment by Zlatkovsky** [comment]
@akrantz , are you going to fix up the test cases to get Travis to pass?
Re. the CODEOWNERS file, you're welcome to add it, though I don't know if it helps much at this stage.  We aren't a big enough project.  Realistically it's still Nico or me that will review the PRs, so I don't know if it adds much...

**Comment by akrantz** [comment]
I started looking into better tests for custom-functions-metadata (https://github.com/OfficeDev/Office-Addin-Scripts/pull/83) but I think for now I could update the script-lab test cases so they pass.

**Comment by akrantz** [comment]
See new pull request: https://github.com/OfficeDev/script-lab/pull/699.

**Pull request closed without merging**
