### PR TITLE
Custom functions metadata 1.0.5

### PR DESCRIPTION
**Pull request by akrantz**
@Zlatkovsky The experimental options are ignored for the repeating parameters so you can remove that code from ScriptLab.

### CODE REVIEW

**Comment by Zlatkovsky** [comment]
@akrantz , looks like this PR failed due to test failures in the CF parser.
Some tests might need to just be removed now if some of the constraints are no longer present; but other tests might actually indicate real issues (e.g., it seems like the new CF parser code allows 3D arrays?)

See the logs at https://travis-ci.com/OfficeDev/script-lab/jobs/220279357#L406

**Comment by akrantz** [comment]
A 3D array is a repeating parameter of ranges. 2D array is a single range. 1D array is a repeating array of number|string|boolean.

**Comment by akrantz** [comment]
We have a lot of test cases now for custom-functions-metadata package. See https://github.com/OfficeDev/Office-Addin-Scripts/tree/master/packages/custom-functions-metadata/test/cases.

**Comment by Zlatkovsky** [comment]
@akrantz , if the CF metadata package has the test cases, that's great.  do you want to remove the Script Lab ones that aren't relevant anymore?  One way or another, we need a change to the Script Lab codebase, so that the tests aren't breaking -- either by fixing or removing the tests.  Without that, I can't merge this PR.

**Comment by akrantz** [comment]
How do I run the tests locally?

**Comment by Zlatkovsky** [comment]
@akrantz :  `yarn workspace editor test`

**Comment by akrantz** [comment]
@Zlatkovsky I'm having problems running tests locally. I've cleaned out node_modules and run "yarn install" again but it doesn't like that my drive letter is lowercase "c" versus uppercase "C".
image

**Comment by Zlatkovsky** [comment]
@akrantz, you might try the `forceConsistentCasingInFileNames` option in the tsconfig, perhaps?  Or just commit it and let Travis build...

**Comment by akrantz** [comment]
@Zlatkovsky I deleted the tests which treated 1D and 3D arrays as errors, since there are now valid types for a repeating parameter for scalar (1D) and range (3d) types. Please review and merge.

**Pull request merged**
